import type { RepoScan } from "./repo-scan.ts";

function list(items: string[]): string {
	return items.length ? items.map((item) => `- ${item}`).join("\n") : "- None detected";
}

function commandLines(scripts: Record<string, string>): string[] {
	return Object.entries(scripts).map(([name, command]) => `- \`npm run ${name}\` — \`${command}\``);
}

export function renderContextMarkdown(scan: RepoScan): string {
	const commands = commandLines(scan.scripts);
	return `# Project Context

## Overview

${scan.packageName} is a repository at \`${scan.root}\`. This file captures stable project context generated by ORGM Pi.

## Current Stack

${list(scan.stack)}

## Repository Map

${list(scan.tree.slice(0, 80))}

## Architecture / Ownership

- Project package: \`${scan.packageName}\`.
- Important files: ${scan.importantFiles.length ? scan.importantFiles.map((file) => `\`${file}\``).join(", ") : "none detected"}.
- Keep package responsibilities explicit when adding new code.

## Commands

${commands.length ? commands.join("\n") : "- No package scripts detected"}

## Configuration and Data

${list(scan.importantFiles)}

## Conventions

- Use ORGM slash command namespace: \`/orgm-*\`.
- Prefer TDD for feature work and bug fixes.
- Run targeted tests before claiming completion.

## Current Roadmap / Phases

- Keep this section updated manually when phases change.
- Use \`RESUME.md\` for active handoff state.

## Do Not Rediscover

- Read this file before re-analyzing the repository from scratch.
- Trust package manifests and scripts listed here unless files changed.
${scan.warnings.length ? `\n## Scan Warnings\n\n${list(scan.warnings)}\n` : ""}`;
}

export function renderAgentsMarkdown(scan: RepoScan): string {
	const commands = commandLines(scan.scripts);
	return `# Agent Instructions

## Project Rules

- Read \`CONTEXT.md\` first for durable project context.
- Read \`RESUME.md\` for current handoff state when continuing work.
- Keep generated ORGM sections intact unless intentionally regenerating them.

## Package Ownership

- Current project package: \`${scan.packageName}\`.
- Keep ownership boundaries documented in \`CONTEXT.md\`.

## Development Workflow

- Use TDD for behavior changes.
- Prefer small commits after green tests.
- Keep slash commands under \`/orgm-*\`.

## Verification Matrix

${commands.length ? commands.join("\n") : "- No scripts detected; use package-specific smoke checks."}

## Safety Notes

- Do not edit ignored/generated directories such as \`node_modules\`, \`dist\`, \`build\`, or \`.git\`.
- Ask before destructive changes.

## Context Files

- \`CONTEXT.md\`: stable project understanding.
- \`AGENTS.md\`: instructions for agents.
- \`RESUME.md\`: current handoff for the next session.
`;
}
