import type { RepoScan } from "./repo-scan.ts";

function normalizeInlineText(value: string): string {
	return value
		.replace(/[\u0000-\u001f\u007f]+/g, " ")
		.replace(/\s+/g, " ")
		.trim()
		.replace(/`+/g, "")
		.replace(/\|/g, "\\|");
}

function codeSpan(value: string): string {
	const normalized = value
		.replace(/[\u0000-\u001f\u007f]+/g, " ")
		.replace(/\s+/g, " ")
		.trim();
	if (!normalized) return "``";
	if (normalized.includes("`")) return normalizeInlineText(normalized);
	return `\`${normalized}\``;
}

function list(items: string[]): string {
	const normalized = items.map(normalizeInlineText).filter(Boolean);
	return normalized.length ? normalized.map((item) => `- ${item}`).join("\n") : "- None detected";
}

function commandLines(scripts: Record<string, string>): string[] {
	return Object.entries(scripts).map(([name, command]) => `- ${codeSpan(`npm run ${name}`)} — ${codeSpan(command)}`);
}

export function renderContextMarkdown(scan: RepoScan): string {
	const commands = commandLines(scan.scripts);
	const packageName = normalizeInlineText(scan.packageName) || "unknown-project";
	const packageNameCode = codeSpan(scan.packageName);
	const root = codeSpan(scan.root);
	const importantFiles = scan.importantFiles.map(codeSpan).filter((file) => file !== "``");
	return `# Project Context

## Overview

${packageName} is a repository at ${root}. This file captures stable project context generated by ORGM Pi.

## Current Stack

${list(scan.stack)}

## Repository Map

${list(scan.tree.slice(0, 80))}

## Architecture / Ownership

- Project package: ${packageNameCode}.
- Important files: ${importantFiles.length ? importantFiles.join(", ") : "none detected"}.
- Keep package responsibilities explicit when adding new code.

## Commands

${commands.length ? commands.join("\n") : "- No package scripts detected"}

## Configuration and Data

${list(scan.importantFiles)}

## Conventions

- Use ORGM slash command namespace: \`/orgm-*\`.
- Prefer TDD for feature work and bug fixes.
- Run targeted tests before claiming completion.

## Current Roadmap / Phases

- Keep this section updated manually when phases change.
- Use \`RESUME.md\` for active handoff state.

## Do Not Rediscover

- Read this file before re-analyzing the repository from scratch.
- Trust package manifests and scripts listed here unless files changed.
${scan.warnings.length ? `\n## Scan Warnings\n\n${list(scan.warnings)}\n` : ""}`;
}

export function renderReviewPrompt(scan: RepoScan): string {
	const safePackage = codeSpan(scan.packageName);
	const commands = commandLines(scan.scripts);
	return `Review this repository and improve the generated ORGM context files.

Project: ${safePackage}
Root: ${codeSpan(scan.root)}

Files to review and improve:
- \`CONTEXT.md\`: durable project overview, stack, architecture, commands, phases, settled decisions.
- \`AGENTS.md\`: concrete instructions for future Pi agents working in this repo.

Start by reading:
- \`CONTEXT.md\`
- \`AGENTS.md\`
- \`README.md\` if present
- package manifests and docs/specs/plans relevant to current work

Detected stack:
${list(scan.stack)}

Detected commands:
${commands.length ? commands.join("\n") : "- No package scripts detected"}

Instructions:
1. Verify generated content against the actual repository.
2. Add missing business/domain context, package ownership, current phases, and known constraints.
3. Keep manual content outside ORGM managed sections intact.
4. Make the files useful enough that the next agent does not need to rediscover the project from scratch.
5. Run a quick verification command if the repo has one, then summarize what changed.
`;
}

export function renderAgentsMarkdown(scan: RepoScan): string {
	const commands = commandLines(scan.scripts);
	const packageName = codeSpan(scan.packageName);
	return `# Agent Instructions

## Project Rules

- Read \`CONTEXT.md\` first for durable project context.
- Read \`RESUME.md\` for current handoff state when continuing work.
- Keep generated ORGM sections intact unless intentionally regenerating them.

## Package Ownership

- Current project package: ${packageName}.
- Keep ownership boundaries documented in \`CONTEXT.md\`.

## Development Workflow

- Use TDD for behavior changes.
- Prefer small commits after green tests.
- Keep slash commands under \`/orgm-*\`.

## Verification Matrix

${commands.length ? commands.join("\n") : "- No scripts detected; use package-specific smoke checks."}

## Safety Notes

- Do not edit ignored/generated directories such as \`node_modules\`, \`dist\`, \`build\`, or \`.git\`.
- Ask before destructive changes.

## Context Files

- \`CONTEXT.md\`: stable project understanding.
- \`AGENTS.md\`: instructions for agents.
- \`RESUME.md\`: current handoff for the next session.
`;
}
